# Generated by Django 6.0.2 on 2026-02-16 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
