# Generated by Django 6.0.2 on 2026-02-15 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('RECHAZADA', 'Rechazada'), ('COMPLETADA', 'Completada'), ('NO_ASISTIO', 'No Asistió'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20)),
                ('google_event_id', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
