# Generated by Django 6.0.2 on 2026-02-15 22:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenda', '0002_initial'),
        ('citas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas_alumno', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cita',
            name='especialista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas_especialista', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cita',
            name='horario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='agenda.horariodisponible'),
        ),
    ]
